#!/usr/bin/env python3
"""
Scaffold a minimal Godot 4 project for the game-gen pipeline.

Usage: scaffold.py <project_path> <title>

Creates project.godot + scenes/main.tscn + scripts/main.gd (stub) + assets/.
Game logic is generated later by GLM 5.3 into scripts/main.gd.
"""
import os
import sys

MAIN_GD_STUB = '''\
extends Node2D

# Game logic is generated by the pipeline into this file.
# Conventions for generated code:
#   - Input via Input.is_key_pressed(KEY_A) / KEY_LEFT etc. (no input map needed)
#   - Placeholder art via ColorRect nodes (no external sprites)
#   - Build the scene programmatically in _ready()

func _ready() -> void:
	pass
'''


def main():
    if len(sys.argv) < 3:
        raise SystemExit("usage: scaffold.py <project_path> <title>")
    proj, title = sys.argv[1], sys.argv[2]
    os.makedirs(os.path.join(proj, "scenes"), exist_ok=True)
    os.makedirs(os.path.join(proj, "scripts"), exist_ok=True)
    os.makedirs(os.path.join(proj, "assets"), exist_ok=True)

    project_godot = f'''config_version=5

[application]
config/name="{title}"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.6")

[display]
window/size/viewport_width=960
window/size/viewport_height=640
'''

    main_tscn = '''[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1"]

[node name="Main" type="Node2D"]
script = ExtResource("1")
'''

    with open(os.path.join(proj, "project.godot"), "w") as f:
        f.write(project_godot)
    with open(os.path.join(proj, "scenes", "main.tscn"), "w") as f:
        f.write(main_tscn)
    with open(os.path.join(proj, "scripts", "main.gd"), "w") as f:
        f.write(MAIN_GD_STUB)
    open(os.path.join(proj, "assets", ".gitkeep"), "w").close()
    print(f"Scaffolded: {proj}")


if __name__ == "__main__":
    main()
